### ISSUE TITLE
DragonFlyBSD Support

### ISSUE THREAD

**Issue by tuxillo** [cirruslabs/cirrus-ci-docs#101]
Hi,

I see you are supporting FreeBSD which is very cool. I was wondering if you have plans on supporting other OSes in the future and if so, what would be the procedure to get the support in?

Thanks,
Antonio Huete

**Comment by fkorotkov** [comment]
What kind of OSes would you love to see? 

It will be pretty easy to add support for any platform to [Google Compute Engine integration](https://cirrus-ci.org/guide/supported-computing-services/#compute-engine): just compile Cirrus CI Go Agent for a necessary platform and check that a startup script can launch the agent. In this case you'll be able to build a VM based of an OS of your choice with any pre-installed software and use this VM with Cirrus CI.

It will be a bit harder for OSS projects since it's not clear where to get VMs for OSes from. In case of FreeBSD, there are already community supported images [on Google Cloud Marketplace](https://console.cloud.google.com/marketplace/details/freebsd-cloud/freebsd-11) which are used. IMO it's by far not the ideal solution because every task need to re-install necessary packages all over again but it's better than nothing. 😅

**Comment by fkorotkov** [comment]
@tuxillo it's not a hard requirement but someone should support the images 🤷‍♂️ Golang team seems interested in it too, will keep an eye on https://github.com/golang/go/issues/23060 to see what they'll come up with.

**Comment by tuxillo** [comment]
Okay thanks, agree on that. Let's see how that Go issue develops.

**Comment by tuxillo** [comment]
Soon we'll be trying to troubleshoot our issues to boot in GCE, hopefully we'll find a solution and we can move forward. I'll keep you guys posted.

**Comment by fkorotkov** [comment]
@tuxillo awesome news! please make sure to check that startup scripts are working to not have the same issue as #359

**Comment by tuxillo** [comment]
We've made some progress, now DragonFly BSD can boot in GCE. Next step is to create official images anyone can use. We'll update this issue once it's done.

**Comment by fkorotkov** [comment]
Wonderful news, congrats! Please make sure DragonFly images will respect startup/shutdown scripts that Cirrus CI depends on for setting up Cirrus CI Agent.

**Comment by daftaupe** [comment]
Hello, I noticed this has been closed, but I don't see any mention of DragonFlyBSD in the closing commit https://github.com/cirruslabs/cirrus-ci-docs/commit/25346a529f1beb4e00b760699c2078033049531f

What else is needed on DragonFly's side ? Create the GCE vm ?

**Comment by daftaupe** [comment]
I see @fkorotkov, thanks. Gonna try to see what needs to be done on GCE's side
