### ISSUE TITLE
`CIRRUS_CHANGE_MESSAGE` to match PR description for incremental pushes

### ISSUE THREAD

**Issue by stuartmorgan** [cirruslabs/cirrus-ci-docs#1029]
## Expected Behavior

In the context of a PR, `CIRRUS_CHANGE_MESSAGE` should be the PR's description, according to the docs:
> Commit message or PR title and description, depending on trigger event (Non-PRs or PRs respectively).

It used to be behave this way, and our CI built tooling around that assumption (allowing us to control minor aspects of our CI behavior by changing the PR description).

## Real Behavior

It is now the case that `CIRRUS_CHANGE_MESSAGE` is reporting the last commit message for incremental commits on a PR.

For instance, in https://github.com/flutter/plugins/pull/6025 I added logging of `CIRRUS_CHANGE_MESSAGE` to debug issues with the tooling mentioned above, and instead of logging that PR's description it logged "Temporary debug logging" which was the commit message of the commit that was added to the PR to add that logging.

# Related Info

This is a (tick one of the following):

- [ ] Website issue
  - Link to page:
- [x] Task issue
  - OS: Docker
  - Task name: `publishable`

**Comment by fkorotkov** [comment]
When you open a PR the `CIRRUS_CHANGE_MESSAGE` is set as you described since it's a separate webhook event (a PR was opened). But when you push a commit to a PR it's a regular push and `CIRRUS_CHANGE_MESSAGE` is the commit message. It might be useful when you found out a typo and used `[ci skip]` to fix it without triggering a build.

`CIRRUS_CHANGE_MESSAGE` description is a bit confusing but the behavior hasn't changed recently. Maybe it's reasonable to change the behavior as you described but other users might rely on the existing behavior.

What kind of behavior are your trying to control with the description? Cirrus has some support for [PR labels](https://cirrus-ci.org/guide/writing-tasks/#required-pr-labels). Do you think exposing them as a comma separated list via `CIRRUS_PR_LABELS` environment variable will be helpful?

**Comment by stuartmorgan** [comment]
> the behavior hasn't changed recently

Huh, I was sure this used to work; I must be remembering wrong what exactly I've seen work.

I agree changing it if that wasn't the original behavior would be problematic.

> What kind of behavior are your trying to control with the description?

It's a bit weird, but we have a CI step that does a best practices presubmit check that by nature will always have false positives (i.e., fails CI for some cases that are fine), for things that were often forgotten during review. We needed a way to explicitly mark a PR so that the test will pass, to make sure that a human has actively looked at it and said it doesn't apply to that PR, rather than it having been forgotten.

The intent was to be able to add something to the PR description to do that. We want it to be stable for the PR rather than per commit.

> Cirrus has some support for [PR labels](https://cirrus-ci.org/guide/writing-tasks/#required-pr-labels). Do you think exposing them as a comma separated list via `CIRRUS_PR_LABELS` environment variable will be helpful?

That sounds perfect; better than the PR description even if that worked the way I thought it had.
