### ISSUE TITLE
Github status API doesn't report Cirrus builds

### ISSUE THREAD

**Issue by asomers** [cirruslabs/cirrus-ci-docs#103]
The status of a Cirrus build is shown graphically on Github's pull request page and on the commits page.  However, it isn't available through the statuses API.  Travis, Appveyor, and BuildBot status reports are all visible through this API, but not Cirrus builds.  Would it be possible for Cirrus to use it?

For example, in the rust-lang/libc repository commit de07759 was built by Travis, Appveyor, and Cirrus.  You can see Cirrrus's checkmark if you click on de07759's green checkmark at https://github.com/rust-lang/libc/commits/auto-libc .  And you can see Cirrus's detailed status at https://github.com/rust-lang/libc/runs/39476297 .  But the API page https://api.github.com/repos/rust-lang/libc/statuses/de0775936049475fe42f71dd7bc9004ec1309317 shows nothing Cirrus-related.

**Comment by fkorotkov** [comment]
Hey @asomers, Cirrus CI is using new GitHub Checks API exclusively. You can use a [different endpoint](https://developer.github.com/v3/checks/suites/#list-check-suites-for-a-specific-ref) to list all Check Suites for a particular ref. Other CI providers are also moving to the Checks API and GitHub advices integrators to move to Checks since they can provide richer feedback.

How do you consume the API response? Is it possible for you to support Checks API?

For a reference [Travis CI also supports Checks API](https://blog.travis-ci.com/2018-05-07-announcing-support-for-github-checks-api-on-travis-ci-com) if you move to [Travis CI App](https://github.com/marketplace/travis-ci).

**Comment by asomers** [comment]
Ahh, thanks.  I was hoping it was something like that.  libc is currently using the Homu merge bot, which doesn't understand check-suites.  But it looks like Bors does.  Maybe we'll switch to Bors.
