### ISSUE TITLE
CIRRUS_PR_LABELS not working

### ISSUE THREAD

**Issue by stuartmorgan** [cirruslabs/cirrus-ci-docs#1054]
## Expected Behavior

`$CIRRUS_PR_LABELS` contains the PR's labels.

See https://github.com/cirruslabs/cirrus-ci-docs/issues/1029 for background. Based on that discussion, I reworked the script in question in our repository to use labels.

## Real Behavior

`$CIRRUS_PR_LABELS` is empty. It was working in my tests in the time, but in a PR yesterday and today it's not working.

See https://github.com/flutter/plugins/pull/6236 we hit this and I added debugging:
- I added https://github.com/flutter/plugins/pull/6236/files#diff-62587956f943bb2503db7bc6dd27d0d888074a1c0ecaab3f570ad611aff0f7bbR87 to echo that environment variable
- https://cirrus-ci.com/task/5203238617088000 shows that the variable is blank

But https://github.com/flutter/plugins/pull/6236 has 8 labels on it.

# Related Info

This is a (tick one of the following):

- [ ] Website issue
  - Link to page:
- [x] Task issue
  - OS: Docker
  - Task name: publishable
  - Script/cache name (if applies): debug_script, version_check_script

**Comment by fkorotkov** [comment]
Cirrus get's the PR info upon PR creation or any  incremental pushes. It seems you have a GitHub Action that adds PR labels **after** creation of a PR with [some delay](https://github.com/flutter/plugins/pull/6236#event-7180618067) so Cirrus will pick them up only for incremental pushes.

One option might be to refactor your scripts to use `CIRRUS_PR` and GitHub's API to fetch the PR labels. But it also might not work because Cirrus can potentially start a task faster than the GHA will run.

A bit more complex but error prone option might be to re-implement the labeler GHA action in Starlark which supports [reading `yaml` files](https://github.com/flutter/plugins/pull/6236#event-7180618067) for the existing `.github/labeler.yml` config, has [`changes_include_only`](https://cirrus-ci.org/guide/programming-tasks/#changes_include_only) for doing the logic and [can be tested](https://cirrus-ci.org/guide/programming-tasks/#is_test).

**Comment by stuartmorgan** [comment]
> It seems you have a GitHub Action that adds PR labels after creation of a PR with https://github.com/flutter/plugins/pull/6236#event-7180618067

The labels in question are added manually, not via actions.

The use case here is that we use it to override a false positive check. Sometimes we realize in advance we'll need it, but other times the flow is that we see the failure, look into it, decide that it's a false positive, and add the label to override it (at which point we want to re-run the test to make it pass).

> Cirrus get's the PR info upon PR creation or any incremental pushes.

Is there some other trigger? Because I know I tested this scenario (push a PR without the label, see the test fail, manually add the label without any other change, re-run the test, see it pass) when I updated the script. If there's something else we can do to trigger getting labels it would help a lot, because an incremental push requires re-running *all* tests, which is an extremely expensive way of getting one cheap test to update its state.

**Comment by stuartmorgan** [comment]
Actually, wait; that can't be the problem.

> or any incremental pushes

If you look at the history of that PR, you'll see the four incremental pushes I made to debug this are all well after all of the labels were added, and none of them is showing up. It is definitely not working as you are describing the expected behavior here (even if what I'm sure I've seen work before isn't intended to work).

**Comment by stuartmorgan** [comment]
We needed to land that PR, so I opened https://github.com/flutter/plugins/pull/6274 for us to use for testing.

**Comment by stuartmorgan** [comment]
Everything is working in that new PR; it definitely was not in the PR I referenced originally.

Have you already changed something at your end to fix this?

**Comment by fkorotkov** [comment]
Yeah, I found a suspicious place which might have caused a race. It was deployed an hour or two ago according to logs so it seems indeed fixed it for you.

**Comment by stuartmorgan** [comment]
Thanks!
