### ISSUE TITLE
Build list shows old time for execution time

### ISSUE THREAD

**Issue by yschimke** [cirruslabs/cirrus-ci-docs#11]
https://cirrus-ci.com/github/yschimke/oksocial

![image](https://user-images.githubusercontent.com/231923/34597231-650dcdfc-f1dd-11e7-9d71-a6778c0fc6ae.png)

https://cirrus-ci.com/build/5733636452122624

![image](https://user-images.githubusercontent.com/231923/34597240-6f233174-f1dd-11e7-92df-1a27b02ddff9.png)

**Comment by fkorotkov** [comment]
That's a tricky question. In your case the second build used caches of the first one and that's why it was so fast.

Internally logic is pretty simple. Cirrus CI updates duration for a build only when build's status changes from `EXECUTION` to a final status(`COMPLETED` or `FAILED`). In this case your build was already in `COMPLETED` state.

IMO it would be not transparent to a user that a duration of an already completed task will just change. Note that when you re-run a task for a build that is already in `COMPLETED` state Cirrus CI doesn't status from `COMPLETED` to `EXECUTING` again. Once build is `COMPLETED` nothing can change the status.

@yschimke, what do you think about it?

**Comment by yschimke** [comment]
Sure - close.  Not a big deal I just found it confusing, see if anyone else reports.
