### ISSUE TITLE
Improve feedback for impossible builds

### ISSUE THREAD

**Issue by rptb1** [cirruslabs/cirrus-ci-docs#1149]
# Description

When I specify a nonexistent image or image_family, the builds just seem to hang for a long time rather than say "nope!"

For example:
- https://cirrus-ci.com/build/6464123383316480 took 15 minutes to fail, probably because there is no "clang:latest" image, but there's no message saying that.
- https://cirrus-ci.com/build/5446771392905216 took 15 minutes to, well, I'm not sure.  It keeps saying "Agent is not responding!"  I suspect there's no FreeBSD on arm64 image available, but there's no message telling me that.

# Context

I have to guess why my builds aren't working and keep pushing experiments to figure things out.  That's not a good use of time.  (Or your resources.)

# Anything Else

Fail fast and clearly. :smiley:

**Comment by fkorotkov** [comment]
It does error with `Container errored with 'ImagePullBackOff: Back-off pulling image "clang:latest"'`. The 15 minutes timeout is intentional since registries like Docker Hub and other have their own incidents from time too time.

IMO this is an issue while the initial config but during normal operation such 15 minutes retries are beneficial in cases of upstream registries having issues.

**Comment by rptb1** [comment]
So, the messages could be improved a great deal.

And how about https://cirrus-ci.com/task/5747445141864448 which just says "Agent not responding!" even after some hours.

**Comment by fkorotkov** [comment]
@rptb1 in this case I don't think FreeBSD image on GCP supports Arm yet and properly handles startup script which is required for bootstrapping Cirrus Agent. I'm not sure how can we improve this messaging in case when initial setup is hitting such edge cases.
