### ISSUE TITLE
Support GCE Spot Instances

### ISSUE THREAD

**Issue by geekflyer** [cirruslabs/cirrus-ci-docs#1189]
# Description

Currently cirrus-ci supports GCE preemptible instances which is great.
However there's now also Spot VMs in GCP (https://cloud.google.com/compute/docs/instances/spot), which is sort of an evolution of Preemptible instances, incl. support for longer running workloads than 24h. See also the soft deprecation notice  of preemptible instances here https://cloud.google.com/compute/docs/instances/preemptible.

Would be great to add support for GCP spot VMs - it's probably just 1 flag?

**Comment by fkorotkov** [comment]
When I initially saw Spot instances I though it just a rebranding but indeed there is slightly different API involved to create Spot instance vs Preemptible. Updated documentation in #1191 for `gce_*` instances and we also switched all our managed instances to Spot instances instead of Preemptible since Spot seems to be recommended now.

**Comment by geekflyer** [comment]
thanks for the quick improvement!
