### ISSUE TITLE
Increase the timeout limit

### ISSUE THREAD

**Issue by pranavjha21** [cirruslabs/cirrus-ci-docs#1204]
# Description

Request to increase the timeout limit for free users from 120m to 180m. 

# Context

Our community depends on Cirrus CI for building projects because we don't have enough powerful hardware as students. Our build fails at 95% due to timeout limit. It would help a lot of people from my community who are using Cirrus CI and have got successful outcomes. Besides this you need to limitise the build minutes per month. Means you guys should add a limit to the build time for free users per month. This would result in a proper utilisation of the service. Hoping for a positive reply !

# Anything Else

...

**Comment by fkorotkov** [comment]
We are not planning to increase the 120 minutes limits. If you build takes longer than 2 hours using maximum 8 CPUs and 24Gb of memory (which is very beefy comparing to regular computers), we believe that in most case such builds can be optimized. Throwing resources at such builds looks like a workaround rather than dealing with the root cause.
