### ISSUE TITLE
Jobs with skipped steps are reported as skipped to GitHub

### ISSUE THREAD

**Issue by davidchisnall** [cirruslabs/cirrus-ci-docs#1280]
We have a CI job where we run tests on PRs as one task and have do a full build and upload an artefact (using an `only_if:` rule) as another task once it's merged.

## Expected Behavior

The job shows up as running on GitHub until the tasks that are running have finished.

## Real Behavior

The tasks that are not running on PR are skipped and, as soon as they are skipped, the entire Cirrus-CI workflow is marked as skipped.

# Related Info
[The .cirrus.yml file](https://github.com/CHERIoT-Platform/llvm-project/blob/cheriot/.cirrus.yml).  

As soon as the `x86_release_task` or `arm_release_task` is skipped, the entire workflow is marked as skipped in a PR.

**Comment by fkorotkov** [comment]
If you are creating a PR from a branch withint the same repository then you might experience this behaviour. This is caused by GitHub caveat that checks are associated to a SHA and not a unique pair (branch, sha). This results that you are seeing skipped checks from the branch build on your pr build.
