### ISSUE TITLE
How to get base git hash?

### ISSUE THREAD

**Issue by gspencergoog** [cirruslabs/cirrus-ci-docs#17]
Looking at the docs, there is an environment variable with a git hash for the currently commit (`$CIRRUS_CHANGE_IN_REPO` - at least I think that's what it is: the doc string "Git SHA" doesn't really tell me anything about which SHA it is), but there doesn't appear to be one that represents the current commit on the source branch.

What I need to be able to do is run a `git diff --name-only` on the range of commits that this Cirrus build represents: for instance, locally I would do `git diff --name-only master..HEAD`.

I've tried exactly that, but the "master" branch doesn't appear to exist on Cirrus builds.  I've tried using `$CIRRUS_DEFAULT_BRANCH` instead of 'master', but that just resolves to 'master'.

Here's what I get when I use `master..HEAD` (or just `master`):
```
⏩ RUNNING: cd .; git diff -U0 --no-color --name-only master..HEAD -- *.dart *.cxx *.cpp *.cc *.c *.C *.h *.java *.mm *.m
fatal: bad revision 'master..HEAD'
```

**Comment by fkorotkov** [comment]
Hey @gspencergoog,

Cirrus CI doesn't have an environment variable like `TRAVIS_COMMIT_RANGE` because it's a bit misleading because `TRAVIS_COMMIT_RANGE` represents range of commits that were pushed. Which means if you push something to a branch the second time, the range won't start from the base ref. `TRAVIS_COMMIT_RANGE` is provided by GitHub API and unfortunately this is the only one they provide.

Above was about why it's missing, now let's see how you can get the range. Cirrus CI does a shallow clone of a single branch with full history but you can limit it by providing `CIRRUS_CLONE_DEPTH`. For your need you can do something similar as [in `flutter/plugins` repository](https://github.com/flutter/plugins/blob/master/script/incremental_build.sh#L12):

```bash
# Make sure there is up-to-date master.
git fetch origin master
BRANCH_BASE_SHA=$(git merge-base --fork-point FETCH_HEAD HEAD)
```

Then `$BRANCH_BASE_SHA...HEAD` will be the range that you want.

Please let me know if it helps you.

**Comment by gspencergoog** [comment]
OK.  If I export an environment variable (e.g. BRANCH_BASH_SHA) in the setup_script section of the .cirrus.yml, will it be in the env for running the test script in the task? (I'm assuming it won't).

If not, then can I invoke commands within the env: section? Like this:
```yml
task:
  env:
    TEST_COMMIT_RANGE: "$(git fetch origin master > /dev/null 2>&1 && git merge-base --fork-point FETCH_HEAD HEAD)..HEAD"
```

**Comment by fkorotkov** [comment]
Scripts in `env` won't be evaluated but seems you figured it out and added it to the right `test_script`.

**Comment by gspencergoog** [comment]
Yes, I did figure it out, Thanks.

**Comment by Hixie** [comment]
Hm, interesting. Flutter uses the tags of recent (past month or so) of commits to figure out its version number, I wonder if only doing a shallow clone will cause problems...
