### ISSUE TITLE
Provide a web API for results

### ISSUE THREAD

**Issue by gspencergoog** [cirruslabs/cirrus-ci-docs#18]
The [Flutter build console](https://flutter-dashboard.appspot.com/build.html) uses a JSON API for [Travis](https://api.travis-ci.org/repos/flutter/flutter/builds) and an XML API for  [Appveyor](https://ci.appveyor.com/api/projects/flutter/flutter/history?recordsNumber=20&branch=master) to get the build results for those builds.

We'd like to do something similar for Cirrus: is such an API available, or do we just need to scrape the HTML?

**Comment by fkorotkov** [comment]
Hey @gspencergoog, there is not much documentation at the moment but there is [GraphQL API](https://github.com/cirruslabs/cirrus-ci-web/blob/master/schema.graphql) available that [Cirrus CI's Front-End](https://github.com/cirruslabs/cirrus-ci-web) is using. You probably want something like:

```graphql
githubRepository(owner: $owner, name: $name) {
  builds(last: 1, branch: $branch) {
      edges {
        node {
          id
          status
      }
    }
  }
}
```

Please follow #12 for updates.

BTW have you considered using GitHub's Status APIs? It might be easier to support just this one API instead of APIs for each reporting system. 😅
