### ISSUE TITLE
Persist new environment variables between script instructions

### ISSUE THREAD

**Issue by fkorotkov** [cirruslabs/cirrus-ci-docs#187]
Right now if you have something like:

```yaml
foo_script: export FOO=bar
echo_script: echo $FOO
```

`echo_script` won't work since `$FOO` is available only within `foo_script`. It will be nice to find a way to persist newly added environment variables.

**Comment by cevich** [comment]
TBH, I wouldn't bother with this because it's possible to set env. vars outside of shell commands (like in built binaries).  The added complexity of always checking the final environment for new/changed env. vars. is a ***lot*** more work than updating the documentation:

```Note: The shell environment is not preserved between scripts, though it does persist across multiple commands in the same section.```

Changing this would also break all existing implementations which already take care to preserve their environments when necessary :grin:

**Comment by fkorotkov** [comment]
Agreed. 👍Wanted to put it out here for discussion because sometime an installation script set env variables like `JAVA_HOME`, `ANDROID_SDK`, etc. Workaround should be either set these environment variables manually in `env` or don't use multiple script instructions.

**Comment by fkorotkov** [comment]
Closing this since it looks like a bit too magical. There a few workarounds like: setting variables manually, using one script instruction or using [Dockerfile as a CI environment](https://cirrus-ci.org/guide/docker-builder/#dockerfile-as-a-ci-environment) with all environment variables set.

**Comment by marnen** [comment]
@fkorotkov How is this magical? Right now, the fact that environment doesn’t persist between scripts means that it’s very difficult for me to break one task down into multiple scripts (because I need to have env variables available for later scripts, but I can’t compute them at the time I’m hard-coding the YAML config), which in turn means that I can’t treat my build process as modular or composable. Also, it’s surprising: what’s the point of having multiple scripts within one task if they *don’t* share the same environment?

I should mention here that I’m testing out Cirrus as a replacement for Travis, which *does* automatically persist env within each task.

**Comment by marnen** [comment]
...and I should also mention that Docker is not an option since this is a Mac build.

**Comment by fkorotkov** [comment]
@marnen Travis does automatically persist env since it doesn't have arbitrary scripts splitting. You only have pre-defined `install_script` and `before_script` which end up in the same generated bash script which gets executed.

Cirrus on the other hand doesn't generate a single script for [all instructions](https://cirrus-ci.org/guide/writing-tasks/#supported-instructions) since, for example, cache instruction is handled directly by Cirrus's Go agent which does the zipping and checksum calculation directly without relying on the environment to have necessary packages pre-installed. This design desiccation allows Cirrus to not rely on the execution environment at all (no need to have `git` or `curl` preinstalled) so you can use even OS-less Docker containers.

Could you please tell me a little more about your project and what you are trying to setup that creates nondeterministic environment variables. Would love to help you! Feel free to response here of if prefer email me directly fedor@cirruslabs.org. 🙌

**Comment by marnen** [comment]
@fkorotkov:

> Travis does automatically persist env since it doesn't have arbitrary scripts splitting. 

Right, and this makes Travis more useful for modularizing a multistep build, since the environment remains the same between steps. I’m not sure I see any benefit to Cirrus’ script splitting. What’s it envisioned for?

> what you are trying to setup that creates nondeterministic environment variables. 

It’s not that the environment variables are nondeterministic, but rather that they’re calculated in a deterministic way from the matrix. I’d like to do

```
env:
  matrix:
    - PROJECT: one
    - PROJECT: two
  PROJECT_PATH: /usr/bin/${PROJECT}
```

but that won’t actually work, will it?

Also, I have a script installing MacPorts and setting environment variables such as PATH so that MacPorts works, and I’d really like to both have that as a separate script step and have the script’s PATH persist.

**Comment by fkorotkov** [comment]
> I’m not sure I see any benefit to Cirrus’ script splitting. What’s it envisioned for?

This splitting will eventually be used in #326 to see week-over-week regressions in scripts plus to detect flakiness of task/instructions). 

> but that won’t actually work, will it?

Your example should work.

> I have a script installing MacPorts and setting environment variables such as PATH so that MacPorts work

Could you just use something like that or you need some other folders in PATH?

```yaml
env:
  PATH: /opt/local/bin:/opt/local/sbin:$PATH
```

**Comment by fkorotkov** [comment]
BTW the magic I was referring too is that the agent can persist output of `printenv` if it's available on `$PATH` in the end of each `script` and then restore it for the next `script` section.

IMO looks a bit magical but seems to be useful for migration like yours. 🤔
