### ISSUE TITLE
Flushing encrypted secrets?

### ISSUE THREAD

**Issue by gspencergoog** [cirruslabs/cirrus-ci-docs#21]
When I encrypt a value, I get something like `ENCRYPTED[<long hex string>]` back that I can use in my script to reconstitute the secret and use it.

If I understand correctly, this long hex string is an internal identifier, and not the actual encoded secret.

This is a good security measure, but this also implies that the encrypted secret is stored somewhere at Cirrus.  What happens if we would like to purge a (now unused) secret from Cirrus's database (to limit exposure to only those secrets actually in use, in case Cirrus is attacked, for instance).  There doesn't appear to be a list of the encrypted IDs anywhere to delete specific ones.

**Comment by fkorotkov** [comment]
@gspencergoog each repository has a uniques 256 bit key for encryption and most importantly Cirrus CI doesn't store a relation between a repository and an encrypted variable. So there is no way to make sure you created the variable in order to delete it.

But we are going to implement a feature that will purge encrypted variables that haven't been used in the last 90 day.

Another feature we are working right now is to give an option to store secrets and encrypted variables outside of `.cirrus.yml` file so they are not presented in your git history and not exposed for public repositories. This feature will further improve Cirrus CI's security.

Will combination of these two features work for you?

**Comment by gspencergoog** [comment]
Yes, the second one seems like the best option to me.

**Comment by fkorotkov** [comment]
Awesome. Will update the docs and close this issues once available.

**Comment by fkorotkov** [comment]
Also it will support having these secrets for the whole organization and not on per-project basis.

**Comment by geekflyer** [comment]
> @gspencergoog each repository has a uniques 256 bit key for encryption and most importantly Cirrus CI doesn't store a relation between a repository and an encrypted variable. So there is no way to make sure you created the variable in order to delete it.
> 
> But we are going to implement a feature that will purge encrypted variables that haven't been used in the last 90 day.
> 
> Another feature we are working right now is to give an option to store secrets and encrypted variables outside of `.cirrus.yml` file so they are not presented in your git history and not exposed for public repositories. This feature will further improve Cirrus CI's security.
> 
> Will combination of these two features work for you?

@fkorotkov what's the status on the ability to store secrets outside of .cirrus.yml? I'm evaluating cirrus for our organization but the current secret management might be a deal breaker.

**Comment by fkorotkov** [comment]
@geekflyer could you please email me at fedor@cirruslabs.org with details about your current setup? Are you looking for something like Kubernetes secrets integration? That's totally makes sense and doable. 👌

**Comment by fkorotkov** [comment]
External secret management will taken care of via integration with HacshiCorp Vault in the next couple of weeks. Subscribe to #1079 for updates.
