### ISSUE TITLE
Ability to deploy to a SSD instead of a standard disk on GCE

### ISSUE THREAD

**Issue by Jnewbon** [cirruslabs/cirrus-ci-docs#264]
# Description

Currently, when using gce_instances the images are deployed to a standard HDD disk however the option to have the instance deployed to an SSD instead would be beneficial for speedier deployments and builds

# Context

SSD would provide faster Deployments, boot and, build times over standard HDDs when using gce_instances

**Comment by ccavolt** [comment]
Does this also apply to gke_container?  I'm testing out node auto-provisioning, and it doesn't look like there's a way to specify the disk type of the generated node pool.  It's still in beta, so I'm guessing either the feature hasn't been implemented, or they expect the deployment to specify the disk type.  Either way, implementing a way to specify the disk type in .cirrus.yml would solve the issue.

**Comment by fkorotkov** [comment]
@ccavolt so you have a mix of node pools with regular SSDs and HDDs? I think this deserves a separate issue to add a more generic support of labels to select nodes for GKE cluster (this will allow to specify preemptible nodes, nodes with GPUs, etc.). Please don't hesitate to create it. 🙌

**Comment by ccavolt** [comment]
@fkorotkov Not really.  I have one node pool that runs Sourcegraph. The other node pools are dynamically generated by node auto-provisioning.  I can't specify the disk type ahead of time because the node pool hasn't been created yet, so it's not a matter of choosing the node pool to run the build on.

Ideally, I'd like for this functionality to work for both GCE and GKE (I don't currently need the functionality you listed, but I do understand its value), but if you feel like it's out of scope, feel free to close the issue and I'll create one specifically for gke_container.

**Comment by fkorotkov** [comment]
@ccavolt Cirrus CI doesn't manage Kubernetes pools, it simply uses Kubernetes API to schedule Kubernetes Jobs which represents tasks. The node auto-provisioning feature claims to respect labels from `nodeSelector` so it should work for your case. Node auto-provisioner will see that some pods need SSDs and will auto-provision the nodes. 👌
