### ISSUE TITLE
Badge incorrectly showing successful build

### ISSUE THREAD

**Issue by mmcc007** [cirruslabs/cirrus-ci-docs#294]
# Expected Behavior

latest build failed and badge in README should show failure
https://cirrus-ci.com/build/4821354109468672

# Real Behavior

latest build failed and badge in README shows success
![Screen Shot 2019-05-18 at 1 32 52 PM](https://user-images.githubusercontent.com/1980785/57974699-861fb100-7971-11e9-9ea3-2dd85f2e6051.png)
https://github.com/brianegan/flutter_architecture_samples

# Related Info
This may be a transient issue, and may not be easily reproducible.
(Also, by the time you look at it, the problem may be gone due to a follow-on build)

**Comment by RDIL** [comment]
It looks like it is cached

**Comment by dotdoom** [comment]
I have the same problem with badge showing failure while it's actually passing now. It's been more than an hour since.

The badge URL returns a HTTP/2 307 (glorified 302) with `cache-control: no-cache` for me. Indeed, the Location header is correctly pointing to Succeeded badge. This might as well be an issue with Camo, in which case there's a way to [purge it manually](https://help.github.com/en/articles/about-anonymized-image-urls), but I couldn't find any pointer.

**Comment by fkorotkov** [comment]
I've reached the GitHub support and they passed the feedback to engineering team but I haven't heard from them. It seems GitHub renderer respects headers of the final link rather than the redirect. If they won't respond with some actions within few days we'll need to workaround it by probably proxing  the badges with the right cache control.

**Comment by mmcc007** [comment]
It looks like it has been resolved
![Screen Shot 2019-05-18 at 1 32 52 PM](https://user-images.githubusercontent.com/1980785/58168556-60c9c600-7c43-11e9-9ce7-dee1f1137550.png)

**Comment by fkorotkov** [comment]
@mmcc007 probably cached got invalidated. Don't see any confirmation from GitHub folks. Let's keep the issue open until we can verify that badge update will be properly propagated to Markdown. 🙌

**Comment by fkorotkov** [comment]
Cirrus proxies the badges now:

```bash
$: curl -I https://api.cirrus-ci.com/github/brianegan/flutter_architecture_samples.svg
HTTP/2 200
date: Wed, 22 May 2019 17:17:50 GMT
cache-control: no-cache
content-type: image/svg+xml
content-length: 948
via: 1.1 google
alt-svc: clear
```

Once cache is invalidated it should work properly.

**Comment by fkorotkov** [comment]
Had to revert the change since it increased CPU load too much on the front-end because of the additional not CDN cacheable IO. Will investigate what to do about it. 😪

**Comment by fkorotkov** [comment]
I've profiled and rewrote the serving part and now it's been running for a few hours without notable CPU spikes as before. Now Cirrus is serving the badges directly and controls caching.

Once Camo caches are invalidated you should see always up-to-date badges.
