### ISSUE TITLE
question: How are authorizations for members of a GitHub organization handled

### ISSUE THREAD

**Issue by MarcoFalke** [cirruslabs/cirrus-ci-docs#328]
Specifically, can members that are not administrators and do not have push access reset builds?

**Comment by fkorotkov** [comment]
The logic is following:
* If this particular user initialized a concrete build then the user can restart the build.
* Otherwise user's permission level is checked via [this API method](https://developer.github.com/v3/repos/collaborators/#review-a-users-permission-level) and only `admin`s and `write`res can restart a build.
