### ISSUE TITLE
Long "SCHEDULED" phase

### ISSUE THREAD

**Issue by connorbrinton** [cirruslabs/cirrus-ci-docs#489]
# Expected Behavior

Once the job has been scheduled, the actual task should start running within a minute, at most.

# Real Behavior

Jobs took up to 14 minutes to start execution after scheduling.

I checked out the logs of the pod to see if I could figure out what was going on, but everything looked fine. The agent had successfully been downloaded, all containers had started up and everything looked ready to go. However, between the (non-init) containers finishing startup and things actually happening in the logs, there was anywhere between 4 to 9 minutes of empty time.

# Related Info

Here's a picture of the scheduling time:

![Screenshot 2019-10-11 13 23 46](https://user-images.githubusercontent.com/1848731/66671686-9ab75b00-ec2a-11e9-99c6-5cf608ec8151.png)

The OS is DockerLinux and here's a link to an example [task](https://cirrus-ci.com/task/5880022312681472) (the most egregious example).

**Comment by RDIL** [comment]
Interesting, the kubernetes cluster uses autoscaling so that kind of time is surprising.

**Comment by fkorotkov** [comment]
There was some instability from 9:21am till 10:22am PST caused by an unexpected spike of too many generated builds from a customer. Which led to slowness of Cirrus and some of the agents were not able to reach out Cirrus for instruction to start the build.  Looks like it was the case ^^ Sorry for the inconvenience. The spike was 10x of the existing load at 9:21am which showed that Cirrus can't scale that fast yet.

Necessary actions are being worked on to handle such spikes.
