### ISSUE TITLE
More detail on how to use the api

### ISSUE THREAD

**Issue by prgwar** [cirruslabs/cirrus-ci-docs#639]
# Question

Ask away!
Hello Team,
I am trying to use the api to trigger the builds. I am on the open source plan but soon will be moving to paid seats. I have got the api token from settings page still I am not able to execute the graphql query. Here is the node js code.

`var request = require("request");
var options = {
  method: "POST",
  url: "https://api.cirrus-ci.com/graphql",
  headers: {
    Accept: "application/json",
    Authorization: "Bearer $apiToken",
    "Content-Type": "application/json",
  },
  body: JSON.stringify({
    query: "{viewer{id}}",
  }),
};
request(options, function (error, response) {
  if (error) throw new Error(error);
  console.log(response);
});
`

I am always getting viewer as null.
Which mutation I should be using for initiating a manual trigger

**Comment by RDIL** [comment]
You can check how the web interface does it: https://github.com/cirruslabs/cirrus-ci-web

**Comment by fkorotkov** [comment]
@prgwar you are getting `viewer` as null because the API token authenticates not as a user but as an "organization".

Here is the mutation web is using https://github.com/cirruslabs/cirrus-ci-web/blob/master/src/components/builds/CreateBuildDialog.tsx#L23-L29. You can see the whole GraphQL schema [here](https://github.com/cirruslabs/cirrus-ci-web/blob/master/schema.graphql) or use [an explorer](https://cirrus-ci.com/explorer).

**Comment by fkorotkov** [comment]
Closing the issue. Please reopen if you have any other questions.
