### ISSUE TITLE
Tasks stuck in "Triggered" state

### ISSUE THREAD

**Issue by connorbrinton** [cirruslabs/cirrus-ci-docs#658]
# Expected Behavior

Tasks should quickly move from "Triggered" to "Scheduled" state.

# Real Behavior

None of our tasks are progressing to the "Scheduled" state, staying stuck as "Triggered". Looking at our GKE workload dashboard, I can confirm that no Cirrus CI tasks are present.

If it's a problem on our end, it would be great to have more diagnostic info presented with the tasks to help us fix any issues 🙂 

# Related Info

- [x] Task issue
  - OS: DockerLinux (GKE)
  - Example Task 1: https://cirrus-ci.com/task/5361631595069440
  - Example Task 2: https://cirrus-ci.com/task/5894343099678720
  - Example Task 3: https://cirrus-ci.com/task/6071808027787264

**Comment by fkorotkov** [comment]
@connorbrinton sorry for a delayed response. Please use email support about time sensitive issues like this one.

I see from the logs that a corresponding GCP service didn't get a status update and then a self-healing mechanism via another "doctor" service picked it up and fixed the issue. I've added some additional logging since current logs doesn't provide some details that could've explain the situation.
