### ISSUE TITLE
Add `cmake` and `gcc` support to MacOS `high-sierra-*` image to reduce CI build time

### ISSUE THREAD

**Issue by ppaulweber** [cirruslabs/cirrus-ci-docs#67]
Hello, is it possible to add the command line tools `cmake` and `gcc` to the `high-sierra-xcode-9.4.1` or directly to the `high-sierra-base` so that it is included in the `high-sierra-xcode-9.4.1` image? 

I'm using `cirrus-ci` to build & test C++ projects and the `osx_instance` consumes a lot of time just to install `cmake` and `gcc`, see the `setup` task at the build log from [example1](https://cirrus-ci.com/task/6035067436531712) or [example2](https://cirrus-ci.com/task/5472117483110400).

Could you please add the following lines to the [high-sierra-base](https://github.com/cirruslabs/osx-images/blob/master/templates/high-sierra-base.json#L38) or [high-sierra-xcode](https://github.com/cirruslabs/osx-images/blob/master/templates/high-sierra-xcode.json#L53) image?
Or could you maybe provide an additional `osx_instance` image with pre-installed `brew`, `xcode`, `cmake`, and `gcc`?

~~~{.json}
brew install cmake
brew install gcc
~~~

**Comment by RDIL** [comment]
I opened a PR to add it to the Mojave images.  Waiting on review from @fkorotkov.

**Comment by fkorotkov** [comment]
Will close the issue once the images will be updated

**Comment by RDIL** [comment]
Should we remove `high-sierra-*` docs since the OS is no longer officially supported?

**Comment by fkorotkov** [comment]
VMs are still available though. 🤔

**Comment by RDIL** [comment]
True, just think that we shouldn't show it to new users so they use the newer images.  My thought is that by doing so, everyone will eventually migrate.

**Comment by fkorotkov** [comment]
And it's been rolled out. 🙌

**Comment by RDIL** [comment]
Great!! 🎉

**Comment by ppaulweber** [comment]
@fkorotkov I think we have to reopen this issue, because I've prepared some [test builds](https://cirrus-ci.com/task/5744043423170560) with the new rolled out `mojave-xcode-10.1` and it seems that `brew` has not adopted link to the correct `gcc` implementation and uses still the symlink to the `gcc` Apple `clang` compiler.

@RDIL I think the installation of `gcc` through `brew` requires an active force linking, e.g. `brew install gcc  && brew link --force gcc` to overwrite the system default symlink of Apple.

**Comment by RDIL** [comment]
That’s not good.  I’ll work on it in a few minutes.

**Comment by ppaulweber** [comment]
@RDIL the ` brew link --force gcc` does not work as expected ... according to the output of `brew` it is correctly symlinked.

**Comment by RDIL** [comment]
Hmm.  Does cmake work?

**Comment by ppaulweber** [comment]
@RDIL yes, `cmake` works, but the xcode tools provide a symlink at ´/usr//bin/{gcc,g++}` to the Apple `clang{,++}` and brew installs the current version of `gcc` e.g. only as `gcc-8` (under `usr/local/bin`) without providing proper symlink adaptions of the `gcc`. I'm just evaluating if it works by applying the following user-defined symlinks in a setup script:

~~~
ln -s /usr/local/bin/gcc-8 /usr/local/bin/gcc
ln -s /usr/local/bin/g++-8 /usr/local/bin/g++
~~~

**Comment by ppaulweber** [comment]
:tada: hurray, it works, now it detects the correct compiler when the command `gcc` is called, due to the default environment path setting by mac OS searching the `/usr/local/bin` path before the `/usr/bin/` path,  see [this build log](https://cirrus-ci.com/task/5488707885858816)

**Comment by RDIL** [comment]
Great to hear!

**Comment by NathaliaLemoine** [comment]
NATHALIA:~ nathalialemoine$ brew install cmake
Warning: Treating cmake as a formula. For the cask, use homebrew/cask/cmake
Warning: You are using macOS 10.13.
We (and Apple) do not provide support for this old version.
You will encounter build failures with some formulae.
Please create pull requests instead of asking for help on Homebrew's GitHub,
Twitter or any other official channels. You are responsible for resolving
any issues you experience while you are running this
old version.

==> Downloading https://github.com/Kitware/CMake/releases/download/v3.24.0/cmake
Already downloaded: /Users/nathalialemoine/Library/Caches/Homebrew/downloads/d6cea1429357d4105c59533925ed74300276fcd5e8c36ae1c9c96b492838b5d5--cmake-3.24.0.tar.gz
Error: Operation already in progress for cmake.formula
Another active Homebrew process is already using cmake.formula.
Please wait for it to finish or terminate it to continue.
NATHALIA:~ nathalialemoine$ brew install cmake
Warning: Treating cmake as a formula. For the cask, use homebrew/cask/cmake
Warning: You are using macOS 10.13.
We (and Apple) do not provide support for this old version.
You will encounter build failures with some formulae.
Please create pull requests instead of asking for help on Homebrew's GitHub,
Twitter or any other official channels. You are responsible for resolving
any issues you experience while you are running this
old version.

==> Downloading https://github.com/Kitware/CMake/releases/download/v3.24.0/cmake
Already downloaded: /Users/nathalialemoine/Library/Caches/Homebrew/downloads/d6cea1429357d4105c59533925ed74300276fcd5e8c36ae1c9c96b492838b5d5--cmake-3.24.0.tar.gz
==> ./bootstrap --prefix=/usr/local/Cellar/cmake/3.24.0 --no-system-libs --paral

I don`t know what to do...
MacOs High Sierra 10.13.6

**Comment by NathaliaLemoine** [comment]
Installing dependencies for watchman: cmake, googletest, gdbm, mpdecimal, sqlite, xz, python@3.10, ninja, libssh2, rust, icu4c, lz4, zstd, boost, fmt, double-conversion, gflags, glog, libevent, pcre, swig, llvm, snappy, folly, cpptoml, bison, libsodium, fizz, wangle, fbthrift and fb303
==> Installing watchman dependency: cmake
==> ./bootstrap --prefix=/usr/local/Cellar/cmake/3.24.0 --no-system-libs --paral

and stop....

**Comment by NathaliaLemoine** [comment]
Installing dependencies for watchman: cmake, googletest, gdbm, mpdecimal, sqlite, xz, python@3.10, ninja, libssh2, rust, icu4c, lz4, zstd, boost, fmt, double-conversion, gflags, glog, libevent, pcre, swig, llvm, snappy, folly, cpptoml, bison, libsodium, fizz, wangle, fbthrift and fb303
==> Installing watchman dependency: cmake
==> ./bootstrap --prefix=/usr/local/Cellar/cmake/3.24.0 --no-system-libs --paral

And stoped
Anyone helps me?

**Comment by ppaulweber** [comment]
@NathaliaLemoine sounds similar to the issue reported at https://github.com/Homebrew/discussions/discussions/2976
