### ISSUE TITLE
[question] What's the state of Arm support? 

### ISSUE THREAD

**Issue by ericoporto** [cirruslabs/cirrus-ci-docs#762]
I am more interested in  MacOS Big Sur 🍎 , but Windows 🔟 and Linux 🐧 would be interesting to be aware of the current situation too.

**Comment by fkorotkov** [comment]
Hey @ericoporto, [Big Sur VMs are already available](https://cirrus-ci.org/guide/macOS/?h=+macos#macos-big-sur) but only Intel ones. We are working on migrading to another virtualization technology which should get ARM support faster then the current one. So once virtualization supports ARM macOS we'll order M1 Mac Minis. For now if you have an M1 device you can use it as a [persistent worker](https://cirrus-ci.org/guide/persistent-workers).

Similar with Windows. Cirrus Only supports server editions of Windows so not even sure if we'll ever have Desktop Windows as part of the cloud offering. But persistent workers should work on both Intel/AMD and ARM Windows instances.

Linux is other area that we are looking at for a long time (see #218). For the OSS cloud offering we use Google Cloud and have a lot of expertise with their Preemptible instances to lower cost of the service we provide for free to OSS. Once GCP has ARM instance it will be matter of hours to add support. In order to use something like AWS Graviton we'll need to implement the same tricks for AWS Spot Instances as we have for the GCP Preemptible Instances. At the moment we have other priorities and simply don't have bandwidth.

Overall I think macOS ARM support will be available ASAP (once virtualization supports it, I've been told in Q1 2021). Linux will follow with more bandwidth (Q2-Q3 or once GCP supports ARM) and Windows ARM is out of plans for now but feel free to create a separate issue similar to #218 to add Windows ARM instances.

Finally, any ARM hardware can be added to Cirrus via [Persistent Workers](https://cirrus-ci.org/guide/persistent-workers) but I think you were interested in the managed-by-us instances.

**Comment by ericoporto** [comment]
Awesome, thanks for the answers!
