### ISSUE TITLE
Limit CPU and RAM for a macOS task

### ISSUE THREAD

**Issue by Minoru** [cirruslabs/cirrus-ci-docs#770]
# Description

Add support for `cpu` and `memory` keys for `osx_instance`. The keys should behave the same as their namesakes for `container` and `freebsd_instance`.

```yaml
osx_instance:
    image: big-sur-base
    cpu: 2
    memory: 4GB
```

# Context

Linux containers and FreeBSD VMs can be given specific amounts of resources using `cpu` and `memory` YAML keys. This helps create smaller tasks, which hopefully make them easier for Cirrus scheduler to fit :) It also allows me to set the same limits on all OSes, so I can run `make -j2` everywhere and know that I'm not underutilizing anything. It'd be nice if macOS provided the same controls.

# Anything Else

It's quite ironic that you're giving me 12 cores (thanks!), and I'm asking for a way to not use them all at once :)

**Comment by fkorotkov** [comment]
Hey @Minoru,

Unfortunately there are some complications from Mac ecosystem that doesn't allow to have that flexibility. 

First, the macOS VMs are in a "suspended" state which means they are already booted and have RAM initialized. In order to have custom CPU we'll need to boot each VM each time with will add additional latency to startup time.

Second, with Big Sur Apple only allows to run at most **two** virtualized macOS instances on one piece of their hardware (before Big Sur there was a bit of grey area in the license agreement) which means if your task will have 2 cores then someone else will need to get 10 cores to fully utilize a Mac Mini that Cirrus is using.

So please try to use `make -j12` to try to fully utilize an instance. I saw some folks define `CPU` environment variable in their matrix and then use it in their scripts `make -j$CPU` and instances `cpu: $CPU` where it's possible to specify custom CPUs. We can probably add predefined `CIRRUS_CPU` environment variable to simplify the setup 🤔

**Comment by Minoru** [comment]
Ah, I figured there might be some limitations on Apple's end. Thanks for the detailed explanation! :+1: 

I think I'll use the `$CPU` trick in my jobs. `CIRRUS_CPU` would be welcome, but isn't essential.
