### ISSUE TITLE
Recommended way to disable builds in a forked repo temporarily?

### ISSUE THREAD

**Issue by MarcoFalke** [cirruslabs/cirrus-ci-docs#771]
When forking a repo, one usually doesn't want ci to run on all pushes (because ci will already run on the opened pull requests against upstream, and on the upstream master branch).

Disabling the builds in the cirrus yaml upstream isn't an option, because everyone who forked the repo will need to modify the upstream yaml, which doesn't scale.

Btw, travis has a setting for this:

![Screenshot_2021-01-29 MarcoFalke btc_nightly - Travis CI](https://user-images.githubusercontent.com/6399679/106257891-7287ad00-621d-11eb-8ecc-46c255ca7357.png)

**Comment by fkorotkov** [comment]
I think the intended way of doing so for GitHub Apps is to configure the app on per-repo level rather then enable the App by default for all repositories on this page: https://github.com/apps/cirrus-ci

One workaround that I saw is to have a top level `only_if: $CIRRUS_REPO_OWNER == bitcoin`. This way forked repositories will have a different owner and therefore won't run builds until creating a PR.

Another option might be to go with GitHub Actions way of disabling builds by default for forks and users will need to explicitly enable it. Cirrus can create a commit status which will explain that the build was skipped since it's a fork and ask if a person wants to enable.

**Comment by MarcoFalke** [comment]
Thanks, https://github.com/apps/cirrus-ci does work for me
