### ISSUE TITLE
Support unit testing CI config

### ISSUE THREAD

**Issue by yogurtearl** [cirruslabs/cirrus-ci-docs#792]
# Description

Provide a way to unit test CI config. 
The CI config tests would run before executing the CI config. 
Probably will want to cache the results of the CI config tests so that you don't have to run them until the CI config is changed.

In psuedo code would look like: 

```
fun test_nightly() {
       config = load(".cirrus.yml")
       confg.simulateClockReaches(DateTime(hour = 1, minutes = 0))

      assertThat(confg.tasksExecuted()).contains(task("nightly_job"))
      assertThat(confg.tasksExecuted().get(task("nightly_job")).scripts).contains(script("benchmark.sh"))
}

fun test_pr_build() {
       config = load(".cirrus.yml")
       confg.assumeTaskExecutionTime("my_pr_task", 300, SECONDS)
       confg.prOpened(DateTime(hour = 1, minutes = 0))
       confg.prCommitPushed(DateTime(hour = 1, minutes = 1))

      assertThat(confg.tasksExecutedToCompletion()).contains(task("my_pr_task"))
      // cancelled when commit was pushed to the PR. 
      assertThat(confg.tasksCancelled()).contains(task("my_pr_task"))
}
```

Might also want to be able to assert things about what was loaded into CI cache, what artifacts where stored, etc. 

# Context

CI config is manually verified by checking that the correct scripts run when the various event trigger them to run. 
Would be nice to be able to programmatically verify that they do what we expect them to do.

**Comment by fkorotkov** [comment]
@yogurtearl we are finalizing support for configuration of Cirrus tasks via Starlark instead of YAML. You can lookup more details [here](https://github.com/cirruslabs/cirrus-cli/blob/master/STARLARK.md).

One of the features of Starlark configuration is ability to load external templates that can help with configuring your repository. For example, for a Go project the whole configuration can look like:

```python
load("github.com/cirrus-templates/golang", "lint_task")

def main(ctx):
    return [detect_tasks(versions=["1.15", "latest"])]
```

Which will auto configure testing, linting and releasing of a typical Go project.

And **Starlark templates can be tested!** You can check details [here](https://github.com/cirruslabs/cirrus-cli/blob/master/STARLARK-TEMPLATING.md#testing) but in a nutshell testing allows to emulate inputs (environment, files in the repository, etc.) and check if generated tasks look expected.

Will something like that work for you? Seem if cover most of your concerns except verifying that caches got the content you expected. 🤔

**Comment by fkorotkov** [comment]
Will close since there is testing for Starlark configs and it's also possible to run Cirrus tasks locally with [Cirrus CLI](https://github.com/cirruslabs/cirrus-cli) to see what kind of caches are created.
