### ISSUE TITLE
Badge 504 responses

### ISSUE THREAD

**Issue by fulder** [cirruslabs/cirrus-ci-docs#803]
I've recently added a lot of badges to the README in this repository: https://github.com/ix-plugin-hub/iocage-plugin-index#plugin-build-status but there seems to be some issues while loading this many task badges where some of the GET requests results in 504 response codes. See devtools screenshot:

<img src="https://user-images.githubusercontent.com/6933250/109693407-e81eca00-7b89-11eb-9f1e-66aafe9e1e29.png" alt="alt text" width=60%>

Is there maybe some kind of rate limiting making this happen?

**Comment by fkorotkov** [comment]
I think there is some issue on the GitHub side when GH is rendering the Markdown. Maybe there are some limits on overall time and how many parallel HTTP requests a single render can do. From the Cirrus side I can only see 200s for the badges to your repository.

If you refresh the page a few times all the badges will appear since they'll hit the cache. I've tweaked caching on Cirrus side a bit so it should better work with a lot of badges like in your case.
