### ISSUE TITLE
KVM based cluster down?

### ISSUE THREAD

**Issue by MarcoFalke** [cirruslabs/cirrus-ci-docs#808]
Is the KVM based cluster down? It seem like macos and docker are working fine.

Example failure: https://cirrus-ci.com/task/5353595466940416

**Comment by fkorotkov** [comment]
Looking into it...

**Comment by fkorotkov** [comment]
Not sure what happened there. I've [just updated the underlying image](https://github.com/cirruslabs/vm-images/commit/6866b833657ce97aa24043ae59700b30f230a564) to be based of Ubunut 2010 and have Java 15 pre-installed. For some reason seems only kvm tasks started failing during the image build. Regular docker builder seems been working.

I've poked the image again and it starter working (I restarted your task). I'll investigate further...

On a side note, I've noticed that you had some performance issue with regular containers and use KVM because of that. [I've recently tweaked the underling GKE cluster](https://twitter.com/fedor/status/1354505744293502980) and highly recommend to try switching back. Regular `container` instances are using faster CPUs and much faster local SSDs now.
