### ISSUE TITLE
Request to increase timeout on community projects by 15 minutes

### ISSUE THREAD

**Issue by IAmSalvaMartini** [cirruslabs/cirrus-ci-docs#825]
A lot of users don't have good hardware and we use cirrusci to build our projects. My current project gets timed out at 99% at 120m and the extra 15 minutes would seal the deal. I'm sure a lot of other users would appreciate this as well

**Comment by fkorotkov** [comment]
Does increasing CPU amount help lower the build time?

**Comment by IAmSalvaMartini** [comment]
I'm on the maximum limit available for free projects, 16 cores and 24GB of RAM. So, that would be a no. The only thing left after 2 hours is packging the build and uploading it, which should be done in around 15 minutes, worst case scenario, 30 minutes

**Comment by IAmSalvaMartini** [comment]
Sorry about closing it and reopening, it was an accidental touch on my phone

**Comment by HemantSachdeva** [comment]
It will be really great if we get more 15 minutes.
I think we both are facing the same issue. My build always gets timed out at 98% even after saving time in syncing, building etc... in every case.
I really appreciate cirrus ci work but it will be 💯 fruitful for me if I get 15 minutes more otherwise it's going to fail at last and am out :(

**Comment by fkorotkov** [comment]
Increasing the timeout is a bit problematic for us since there are a couple of optimizations regarding orchestrating of the containers.

In the meantime you have three options:
* Optimize your build to fit within 2 hours
* Use either [compute credits](https://cirrus-ci.org/pricing/#compute-credits) or a 1[0$/month plan for personal repositories which will give you containers with up to 30 CPUs](https://cirrus-ci.org/faq/#are-there-any-limits).
* [Bring your own infrastructure](https://cirrus-ci.org/guide/supported-computing-services/). You can get $300 on [GCP Free Tier](https://cloud.google.com/free).

PS I checked [your repository](https://github.com/IAmSalvaMartini/aosp-building) and it seems in a bit grey area. The community clusters of Cirrus CI (the one provided for free) are intended for open source projects which want to continuously run tests and other integrations. In your case it seems you are using the community clusters as a build farm.

**Comment by IAmSalvaMartini** [comment]
I see. Thank you for your time and I'll try to optimise it further as best as possible. As for the build farm, I'll be switching to fortnightly cron builds so as to not abuse the community clusters.
