### ISSUE TITLE
Display time it takes to download docker images

### ISSUE THREAD

**Issue by anarazel** [cirruslabs/cirrus-ci-docs#923]
Hi,

When a task uses a big-ish docker container, it can take a while to start. E.g. in https://cirrus-ci.com/task/5377418673258496 I see "Scheduled in 08:06".

It's to be expected that bigger images take longer. However, the same container previously took less time. It'd be easier to analyze cases like this if the docker pull on the host showed the pull on the container host as a execution step.

Presumably that'd be easier for the windows case, were I think you run the docker hosts yourself, compared to linux containers running on GKE. But it's also a lot easier to have small linux containers...

Relatedly, it'd be nice if the meaning of "scheduled"  on tasks could be clarified - it sounds like it is the time until a compute resource for a task has been allocated, but afaict it is the time until the agent actually runs...

Regards,

Andres

**Comment by fkorotkov** [comment]
Will be fixed by #923

**Comment by anarazel** [comment]
> Will be fixed by #923

@fkorotkov I assume you intended to link to some PR? Because #923 is just this issue?

**Comment by fkorotkov** [comment]
Whoops. Yes, #402 is the issue.

**Comment by anarazel** [comment]
Ah - in my case it was a windows docker image that's taking a long time to start... Afaict the new output isn't visible there?

**Comment by ericoporto** [comment]
@fkorotkov ,I can't find the time in the Debugging Information agent logs for the Windows to load the docker image. Is this something only in Linux?

**Comment by fkorotkov** [comment]
This is only supported for Kubernetes based instances like `{gke,eks,oke}_container`. For the "managed-by-us" instances it only supported for `container` and `arm_container`.

Our `windows_container` is backed by a VM because there is such variety of different images is used that it doesn't make sense to use a Kubernetes cluster. Unlikely an image will be actually cached or we'll need some disks with petabytes of storage.
